//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18331
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public sealed class Suburbia
{

    private Suburbia ()
    {
        m_eventBus = new EventBus ();
    }

    private EventBus m_eventBus;
    private RealEstateMarket m_market;
    private TileManager m_game_manager;

    public void StartGame (int p_nb_players)
    {
        m_market = new RealEstateMarket (p_nb_players);
        TileManager.LoadSetupTiles(m_market.Stacks.LoadedTiles);
        TileView.InitTextures();
        m_game_manager = new TileManager(p_nb_players);
    }

    public static Suburbia App {
        get {
            return m_instance;
        }
    }

    public static EventBus Bus {
        get {
            return m_instance.m_eventBus;
        }
    }

    public static RealEstateMarket Market {
        get {
            return m_instance.m_market;
        }
    }

    public static TileManager Manager {
        get {
            return m_instance.m_game_manager;
        }
    }

    private static readonly Suburbia m_instance = new Suburbia ();
}


