//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18331
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using SimpleJSON;

public class Trigger
{
		private readonly TileType m_type;
		private readonly ETileScope m_scope;
		private readonly ETileWhen m_when;
		private readonly Effect m_effect;

		public static Trigger LoadFromJson (JSONClass p_json)
		{
				// TODO
				return null;
		}

		public Trigger (ETileScope p_scope, ETileWhen p_when, TileType p_type, Effect p_effect)
		{
				m_type = p_type;
				m_scope = p_scope;
				m_when = p_when;
				m_effect = p_effect;
		}

		public ETileScope scope {
				get {
						return this.m_scope;
				}
		}

		public TileType type {
				get {
						return this.m_type;
				}
		}

		public ETileWhen when {
				get {
						return this.m_when;
				}
		}

		public Effect effect {
				get {
						return this.m_effect;
				}
		}

		public void Apply (Player p_owner, bool p_adjacent)
		{
				// TODO ADJACENT_TO_OWN_LAKE
				if (m_scope == ETileScope.ADJACENT && !p_adjacent)
						return;

				m_effect.Apply (p_owner);
		}
}


