//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18331
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;


public class TriggerInstance
{
		private Trigger m_trigger;
		private TileInstance m_tile_owner;

		public TriggerInstance (Trigger p_trigger, TileInstance p_tile_owner)
		{
				m_trigger = p_trigger;
				m_tile_owner = p_tile_owner;
		}

		public void Apply (TileInstance p_other)
		{
				m_trigger.Apply (m_tile_owner.owner, m_tile_owner.IsAdjacentTo (p_other));
		}

		public void Apply (Player p_owner, int n)
		{
			m_trigger.Apply (p_owner, n);

	        Suburbia.Bus.FireEvent(new EventResourceAdjustment(p_owner, m_trigger.effect.resource, m_trigger.effect.value * n, m_tile_owner));
		}

		public TileInstance owner {
				get {
						return this.m_tile_owner;
				}
		}

		public Trigger trigger {
				get {
						return this.m_trigger;
				}
		}
}


