//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18331
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Newtonsoft.Json.Linq;

public class Util
{
		private Util ()
		{
		}

		public static T getValue<T> (JObject p_json, string p_attribute)
		{
				//JToken o = JToken.Parse (p_json);
				return (T)p_json.SelectToken (p_attribute);
		}

		public static T parseEnum<T> (string p_value)
		{
				return (T)Enum.Parse (typeof(T), p_value, true);
		}

		public static T tryEnum<T> (string p_value)
		{
				try {
						return 	(T)Enum.Parse (typeof(T), p_value, true);
				} catch (ArgumentException) {
						return (T)Enum.Parse (typeof(T), "NULL", true);
				}
		}
}

