//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18331
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class TileView
{

    private GameObject m_object;

    public TileView (TileInstance p_tile)
    {
        m_object = UnityEngine.Object.Instantiate(Resources.Load("Prefabs/Green_tile")) as GameObject;
    }
}
